//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ESystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ex_systemEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ex_systemEntities object using the connection string found in the 'ex_systemEntities' section of the application configuration file.
        /// </summary>
        public ex_systemEntities() : base("name=ex_systemEntities", "ex_systemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ex_systemEntities object.
        /// </summary>
        public ex_systemEntities(string connectionString) : base(connectionString, "ex_systemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ex_systemEntities object.
        /// </summary>
        public ex_systemEntities(EntityConnection connection) : base(connection, "ex_systemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<esAnswer> esAnswers
        {
            get
            {
                if ((_esAnswers == null))
                {
                    _esAnswers = base.CreateObjectSet<esAnswer>("esAnswers");
                }
                return _esAnswers;
            }
        }
        private ObjectSet<esAnswer> _esAnswers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<esNode> esNodes
        {
            get
            {
                if ((_esNodes == null))
                {
                    _esNodes = base.CreateObjectSet<esNode>("esNodes");
                }
                return _esNodes;
            }
        }
        private ObjectSet<esNode> _esNodes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the esAnswers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToesAnswers(esAnswer esAnswer)
        {
            base.AddObject("esAnswers", esAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the esNodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToesNodes(esNode esNode)
        {
            base.AddObject("esNodes", esNode);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ex_systemModel", Name="esAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class esAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new esAnswer object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idNodeQuestion">Initial value of the idNodeQuestion property.</param>
        /// <param name="data">Initial value of the data property.</param>
        /// <param name="idNodeSubject">Initial value of the idNodeSubject property.</param>
        public static esAnswer CreateesAnswer(global::System.Int32 id, global::System.Int32 idNodeQuestion, global::System.String data, global::System.Int32 idNodeSubject)
        {
            esAnswer esAnswer = new esAnswer();
            esAnswer.id = id;
            esAnswer.idNodeQuestion = idNodeQuestion;
            esAnswer.data = data;
            esAnswer.idNodeSubject = idNodeSubject;
            return esAnswer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idNodeQuestion
        {
            get
            {
                return _idNodeQuestion;
            }
            set
            {
                OnidNodeQuestionChanging(value);
                ReportPropertyChanging("idNodeQuestion");
                _idNodeQuestion = StructuralObject.SetValidValue(value, "idNodeQuestion");
                ReportPropertyChanged("idNodeQuestion");
                OnidNodeQuestionChanged();
            }
        }
        private global::System.Int32 _idNodeQuestion;
        partial void OnidNodeQuestionChanging(global::System.Int32 value);
        partial void OnidNodeQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, false, "data");
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.String _data;
        partial void OndataChanging(global::System.String value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idNodeSubject
        {
            get
            {
                return _idNodeSubject;
            }
            set
            {
                OnidNodeSubjectChanging(value);
                ReportPropertyChanging("idNodeSubject");
                _idNodeSubject = StructuralObject.SetValidValue(value, "idNodeSubject");
                ReportPropertyChanged("idNodeSubject");
                OnidNodeSubjectChanged();
            }
        }
        private global::System.Int32 _idNodeSubject;
        partial void OnidNodeSubjectChanging(global::System.Int32 value);
        partial void OnidNodeSubjectChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ex_systemModel", Name="esNode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class esNode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new esNode object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idNode">Initial value of the idNode property.</param>
        /// <param name="isLeaf">Initial value of the isLeaf property.</param>
        /// <param name="idParentNode">Initial value of the idParentNode property.</param>
        /// <param name="isRemove">Initial value of the isRemove property.</param>
        public static esNode CreateesNode(global::System.Int32 id, global::System.Int32 idNode, global::System.Boolean isLeaf, global::System.Int32 idParentNode, global::System.Boolean isRemove)
        {
            esNode esNode = new esNode();
            esNode.id = id;
            esNode.idNode = idNode;
            esNode.isLeaf = isLeaf;
            esNode.idParentNode = idParentNode;
            esNode.isRemove = isRemove;
            return esNode;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idNode
        {
            get
            {
                return _idNode;
            }
            set
            {
                OnidNodeChanging(value);
                ReportPropertyChanging("idNode");
                _idNode = StructuralObject.SetValidValue(value, "idNode");
                ReportPropertyChanged("idNode");
                OnidNodeChanged();
            }
        }
        private global::System.Int32 _idNode;
        partial void OnidNodeChanging(global::System.Int32 value);
        partial void OnidNodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, true, "data");
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.String _data;
        partial void OndataChanging(global::System.String value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isLeaf
        {
            get
            {
                return _isLeaf;
            }
            set
            {
                OnisLeafChanging(value);
                ReportPropertyChanging("isLeaf");
                _isLeaf = StructuralObject.SetValidValue(value, "isLeaf");
                ReportPropertyChanged("isLeaf");
                OnisLeafChanged();
            }
        }
        private global::System.Boolean _isLeaf;
        partial void OnisLeafChanging(global::System.Boolean value);
        partial void OnisLeafChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idParentNode
        {
            get
            {
                return _idParentNode;
            }
            set
            {
                OnidParentNodeChanging(value);
                ReportPropertyChanging("idParentNode");
                _idParentNode = StructuralObject.SetValidValue(value, "idParentNode");
                ReportPropertyChanged("idParentNode");
                OnidParentNodeChanged();
            }
        }
        private global::System.Int32 _idParentNode;
        partial void OnidParentNodeChanging(global::System.Int32 value);
        partial void OnidParentNodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isRemove
        {
            get
            {
                return _isRemove;
            }
            set
            {
                OnisRemoveChanging(value);
                ReportPropertyChanging("isRemove");
                _isRemove = StructuralObject.SetValidValue(value, "isRemove");
                ReportPropertyChanged("isRemove");
                OnisRemoveChanged();
            }
        }
        private global::System.Boolean _isRemove;
        partial void OnisRemoveChanging(global::System.Boolean value);
        partial void OnisRemoveChanged();

        #endregion

    }

    #endregion

}
